# Generated by Django 2.2.1 on 2019-05-17 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_functioncrudmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FunctionCrudModel',
        ),
    ]
